---
- hosts: all
  become: yes
  order: reverse_sorted

  tasks:

    - name: Install system updates for Red Hat based systems
      yum:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution == "Fedora"

    - name: Install system updates for ubuntu systems
      apt:
        name: '*'
        state: latest
        update_cache: yes
       #cache_valid_time: 3600
      when:
        - ansible_os_family == "Debian"
        - ansible_distribution == "Ubuntu"
